### ISSUE TITLE
How can I send to a especific user? 

### ISSUE THREAD

**Issue by donascimentomarcelo** [NetoDevel/sdk-onesignal-java#3]
Hi!
I would like know how can I send a notification to an especific user. 
Example, an user that is logged on app. Where I send the email or id?
Thanks man!

**Comment by netodevel** [comment]
Look at the Readme.MD, you can set
`.withIncludedPlayerIds(Arrays.asList("5aa94fdc-f6ba-4c11-8cc2-ffda8e30a074", "OTHER PLAYER ID"))`
